version: '3'
services:
    playground:
        container_name: 'CMIPIU'
        hostname: 'python'

        build: .
        shm_size: '32gb'
        restart: always
        working_dir: '/kaggle'
        tty: true
        volumes:
            - type: bind
              source: ../
              target: /kaggle
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]